export { default as Intro } from './intro/Intro'
export { default as About } from './about/About'
export { default as Portfolio } from './portfolio/Portfolio'
export { default as Contacts } from './contact/Contact'
export { default as Toggle } from './toggle/Toggle'